Repository AutoScout24/as24-custom-events, pull requests merged in 2021-01, with the labels that each got.

#77 Ugaa 325 additional login events
  src/pages/loginDialog.ts
Labels: enhancement, release:enhancement

#78 Forcing a new release
  README.md
Labels: bug, release:bugfix

#79 Add searchId initialized event
  __tests__/pages/__snapshots__/listpage.test.ts.snap
  __tests__/pages/listpage.test.ts
  src/pages/listpage.ts
Labels: release:enhacement, release:enhancement
